### ISSUE TITLE
(Ring) timers continue counting (invisibly) when paused

### ISSUE THREAD

**Issue by Tschis** [vsz/Cooldown-Overlay#7]
Activating a life ring will start counter, if you change rings, the timer will be paused and the new ring will start counting down.

However, if you use second ring for 10s and switch back to life ring, the timer will jump 10s down instead of continually decrement.

Did not test if this is true for other cooldowns.

**Comment by vsz** [comment]
That is the intended behaviour. When equipping items that are not brand new, Tibia reduces countdown by 6 seconds. Check method 'track' on 'TrackedEquipment' class.
Also, I suggest you try tracking actual items in game with the overlay active and verify that the cooldown on the overlay and in-game is similar.

**Comment by Tschis** [comment]
I did around 6 seconds testing and did not realize that was the reason.
Thanks!
